server:
  port: 3000

spring:
  profiles:
    active: test
  application:
    name: admin-system
  #指定静态资源的路径
  resources:
    static-locations: classpath:/static/,classpath:/views/

  ###ThymeLeaf配置
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: LEGACYHTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    suffix: .html
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/

mybatis:
  mapper-locations: "classpath*:mapper*/**/*.xml"
  config-location: "classpath:mybatis-config.xml"

props:
  sql.show: true

feiji:
  name: "plane"
  length: 100
  weight: 100

tanke:
  name: "tank"



